export { default as FacebookIcon } from "./facebook.png";
export { default as InstagramIcon } from "./instagram.png";
export { default as Logo } from "./Minor Logo.png";
export { default as Home } from "./home.png";
export { default as Profile } from "./profile.png";
export { default as ShowPassword } from "./showPassword.png";
export { default as ErrorIcon } from "./error.png";
export { default as Flower } from "./Leaves.png";
export { default as Edit } from "./edit.png";
export { default as Checked } from "./checked.png";
export { default as Unchecked } from "./unchecked.png";
